### ISSUE TITLE
Future timed out after

### ISSUE THREAD

**Issue by sven-hash** [alephium/explorer-backend#258]
Error log that appear at start (jar or docker). A restart solve the error but still coming back

```
2022-06-07 17:28:59,729 [main]          INFO  o.a.explorer.Main$                     - Starting Application                          
2022-06-07 17:28:59,922 [main]          INFO  o.a.explorer.Main$                     - Build info: name: explorer-backend-app, scalaV
ersion: 2.13.3, sbtVersion: 1.6.2, commitId: d3799787afdceee465628de69e5b662854b4e357, branch: d3799787afdceee465628de69e5b662854b4e3
57, releaseVersion: 1.6.9                                                                                                            
2022-06-07 17:29:03,244 [-dispatcher-6] INFO  a.e.s.Slf4jLogger                      - Slf4jLogger started                           
2022-06-07 17:29:06,285 [main]          INFO  o.a.e.p.DBInitializer$                 - Create Tables                                 
2022-06-07 17:29:06,442 [main]          INFO  c.z.h.HikariDataSource                 - db.db - Starting...                           
2022-06-07 17:29:06,502 [main]          INFO  c.z.h.HikariDataSource                 - db.db - Start completed.                      
2022-06-07 17:29:07,854 [main]          DEBUG i.m.c.u.i.l.InternalLoggerFactory      - Using SLF4J as the default logging framework  
2022-06-07 17:29:08,466 [-dispatcher-6] INFO  o.a.e.p.Migrations$                    - Migrating                                     
2022-06-07 17:29:08,603 [-dispatcher-6] INFO  o.a.e.p.DBInitializer$                 - Create Indexes                                
Exception in thread "main" java.util.concurrent.TimeoutException: Future timed out after [5 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.Await$.result(package.scala:124)
        at org.alephium.explorer.util.FutureUtil$AwaitUtils.await(FutureUtil.scala:29)
        at org.alephium.explorer.Application.<init>(Application.scala:67)
        at org.alephium.explorer.Main$.delayedEndpoint$org$alephium$explorer$Main$1(Main.scala:75)
        at org.alephium.explorer.Main$delayedInit$body.apply(Main.scala:35)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at org.alephium.explorer.Main$.main(Main.scala:35)
        at org.alephium.explorer.Main.main(Main.scala)
        ```

**Comment by simerplaha** [comment]
Replicated locally: `Exception in thread "main" java.util.concurrent.TimeoutException: Future timed out after [10 seconds]`

**Cause**: Occurs due to the `await` in `Application` which timeout. 

Quick fix: Increased the timeout to `5.minutes` in the commit above. This timeout should be really be taken as an input from the configuration or as command line input. Which way do we prefer?

**Comment by simerplaha** [comment]
PR #255 should also account for this timeout in `Main.scala`.
